# vim: ft=yaml

name: 'Saltstack'

on: [push, pull_request]

jobs:
  saltstack:
    name: 'Saltstack'
    runs-on: ubuntu-22.04
    steps:
    - name: Install Chef Inspec
      run: |
        wget https://packages.chef.io/files/stable/inspec/5.22.3/ubuntu/20.04/inspec_5.22.3-1_amd64.deb
        sudo dpkg -i inspec_5.22.3-1_amd64.deb
        rm inspec_5.22.3-1_amd64.deb
        sudo inspec --chef-license=accept-silent

    - name: Install salt-minion
      run: |
        sudo wget -O /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
        echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" | sudo tee /etc/apt/sources.list.d/salt.list
        sudo apt-get update
        sudo apt-get install -y salt-minion

    - uses: actions/checkout@v1
    - name: Apply state
      run: |
        sudo mkdir /srv/postgresql
        sudo cp -r * /srv/postgresql
        sudo cp tests/top.sls /srv/
        sudo salt-call state.apply \
          --local --log-file=/dev/null --retcode-passthrough --file-root /srv --pillar-root \
          /srv/postgresql/tests/pillar

    - name: Run inspec
      run: |
        sudo inspec exec tests/integration/postgresql
